[build]
  command = "python -m venv venv && venv/Scripts/activate && python -m pip install -r requirements.txt && python app.py"
  publish = "C:\Users\aksha\ML\Major Project\VisionVerse.ai\app.py"

[build.environment]
  PYTHON_VERSION = "3.10"
